#import = ["/Users/nyahahanoha/.config/alacritty/dracula.toml"]
import = ["/Users/nyahahanoha/.config/alacritty/aura.toml"]

[env]
TERM = "alacritty"

[font]
size = 18.0

[font.bold]
family = "Meslo LG L"
style = "Bold"

[font.bold_italic]
family = "Meslo LG L"
style = "Bold Italic"

[font.italic]
family = "Meslo LG L"
style = "Italic"

[font.normal]
family = "Meslo LG L"
style = "Regular"

[shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "/opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux -u",
]

[window]
opacity = 0.7

[window.padding]
x = 3
y = 1

[keyboard]
bindings = [
  { key = "¥", chars = "\\" },
]
